dist: trusty

language: python
python: 3.6

matrix:
    include:
        - os: linux

addons:
  apt_packages:
    - pandoc

cache: pip

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests

install:
  - pip install lightkurve
  - pip install tensorflow
  - pip install astropy
  - pip install astroquery
  - pip install tqdm
  - pip install fitsio
  - pip install sphinx
  - pip install nbsphinx
  - pip install cython
  - pip install codecov
  - pip install coverage
  - python setup.py install

script:
  - python setup.py develop
  - echo "skipping tests"

after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
